### PR TITLE
fix to install gopls correctly under Windows

### LINKED ISSUE #6: does not install gopls on windows
I get `'GOPATH' is not recognized as an internal or external command` after installing the extension.

### LINKED ISSUE #75: Failed to install
I can't install this plugin. Here's the error message:

```
[coc.nvim] Failed to install 'gopls'
[coc.nvim] Error: exited with 1
[coc.nvim] Failed to install 'gomodifytags'
[coc.nvim] Failed to install 'gotests'
```

### PR DESCRIPTION
**Pull request by wsw0108**
fix #6 , fix #75 

And this may also fix installation problem for other shell like fish.

### CODE REVIEW

File: src/utils/tools.ts [hunk 1]
```diff
@@ -67,10 +67,14 @@ async function goRun(args: string): Promise<boolean> {
   const gobin = await configDir('bin')
 
   const env = { GOBIN: gobin, GOPATH: gopath, GO111MODULE: 'on' }
-  const cmd = `${formatCmd(env, `go ${args}`)}`
```
Comment (josa42) [inline src/utils/tools.ts:70]: Since `formatCmd()` isn't use anymore, could remove it from `tools.ts` and delete `tools.test.ts`?
